<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Poker Hands</h1>
        <div>
            <form method="post" enctype="multipart/form-data" action="/upload-hands">
                <p>
                    <label>Add file (single): </label><br/>
                    <input type="file" name="hands_file"/>
                </p>

                <p>
                    <input type="submit"/>
                </p>
            </form>

            <h2>Games won by player</h2>
            <table style="width:50%; border:1px solid gainsboro;">
                <thead>
                <tr><th>Player 1</th><th>Player 2</th></tr>
                </thead>
                <tbody>
                <tr>
                    <td><?= $playerOneCount; ?></td><td><?= $playerTwoCount ?></td>
                </tr>
                </tbody>

            </table>
        </div>


    </body>
</html>
